name: 'my_project'
version: '1.0'
config-version: 2

profile: 'elementary'

vars:
  'dbt_date:time_zone': 'Europe/Madrid'

models:
  ## see docs: https://docs.elementary-data.com/
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"

